import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

function generatePassword() {}

export default function Home() {
  return (
    <>
      <Head>
        <title>Password generator</title>
        <style>{`
          html {
            font-family: ${inter.style.fontFamily};
          }
        `}</style>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="min-h-screen">
        <div className="min-h-screen flex flex-col justify-center text-center">
          <div className="text-2xl font p-10 font-bold">Password Generator</div>
          <div>
            <form>
              <div className="flex flex-col justify-center">
                <div className="flex justify-center gap-5">
                  <label htmlFor="length">Password Length:</label>
                  <input className="rounded-md" type="number" id="length" min="8" max="64" value="16" />
                </div>
                <div className="flex justify-center gap-5">
                  <label htmlFor="uppercase">Include Uppercase Letters</label>
                  <input type="checkbox" id="uppercase" />
                </div>
                <div className="flex justify-center gap-5">
                  <label htmlFor="lowercase">Include Lowercase Letters</label>
                  <input type="checkbox" id="lowercase" checked />
                </div>
                <div className="flex justify-center gap-5">
                  <label htmlFor="numbers">Include Numbers</label>
                  <input type="checkbox" id="numbers" />
                </div>
                <div className="flex justify-center gap-5">
                  <label htmlFor="symbols">Include Symbols</label>
                  <input type="checkbox" id="symbols" />
                </div>
                <button className="py-8" type="button" onClick={generatePassword}>
                  Generate Password
                </button>
                <textarea id="password" className="max-w-xs mx-auto bg-zinc-700 rounded-lg" readOnly></textarea>
              </div>
            </form>
            <div className="text-gray-400 p-10">
              Have you ever wondered "<i>Is my password strong enough?</i>". Well, here you can generate one.
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
